services:
  fastapi:
    container_name: fastapi
    build: .
    ports:
      - "8000:8000" # 🔓 Host의 스프링이 찌를 수 있도록 포트 개방
    depends_on:
      - qdrant-db
    restart: always

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: always

volumes:
  qdrant_data:
